# Generated by Django 2.2 on 2019-04-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetydatasheet',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
